### ISSUE TITLE
"Still" getting SegFaults with DLite v0.4.x

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-dlite#179]
As seen in [this CI run](https://github.com/EMMC-ASBL/oteapi-dlite/actions/runs/6377786627/job/17307092835?pr=176#step:5:74), DLite (now v0.4.1) is giving a segmentation fault when running the tests in a unix system (not getting segmentation fault for the tests running on a Windows system!).

This should be fixed in DLite - cannot be fixed in this repository.

**Comment by jesper-friis** [comment]
Can you please make a reproducible example that can be debugged where the error turns up.

I cannot reproduce this issue, neither with Python 3.9 or 3.10. I have also tried to run the oteapi-dlite tests with act, that also works fine.

**Comment by CasperWA** [comment]
I only have the referenced CI run to reference, unfortunately (see the link in the original post).

**Comment by jesper-friis** [comment]
If running pytest via gdb, it doesn't segfault: https://github.com/EMMC-ASBL/oteapi-dlite/pull/183

I also tried to run the following Dockerfile

```
FROM ubuntu:22.04

RUN apt-get update --fix-missing
RUN apt-get install -y python3 python3-pip

COPY requirements.txt requirements_dev.txt ./
COPY oteapi_dlite oteapi_dlite/
COPY tests tests/

RUN python3 --version
RUN python3 -m pip install -U pip
RUN pip install -U setuptools wheel
RUN pip install -U -r requirements.txt -r requirements_dev.txt

COPY README.md requirements_docs.txt setup.py setup.cfg tasks.py pyproject.toml ./
RUN pip install -U .
RUN pytest -vvv --cov-report=xml
```

This fails for pytest, not with segfault, but because pytest tries to access a non-existing file descriptor. This is most likely a bug in pytest and not in dlite.

**Comment by CasperWA** [comment]
I'd think a bug in DLite is more likely than one in pytest. Or rather, a misunderstanding of how to use pytest.

**Comment by CasperWA** [comment]
It's still happening. See [this CI run](https://github.com/EMMC-ASBL/oteapi-dlite/actions/runs/6485681974/job/17612300000?pr=176#step:5:74). Note that the updated DLite version here is based on the `ci/dependabot-updates` branch. These are the installed Python packages:
`DLite-Python-0.4.1 Pillow-10.0.1 agraph-python-102.0.0 amqp-5.1.1 astroid-3.0.0 bcrypt-4.0.1 billiard-4.1.0 celery-5.3.4 certifi-2023.7.22 cffi-1.16.0 cfgv-3.4.0 charset-normalizer-3.3.0 click-8.1.7 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.3.0 coverage-7.3.2 cryptography-41.0.4 dill-0.3.7 diskcache-5.6.3 distlib-0.3.7 et-xmlfile-1.1.0 exceptiongroup-1.1.3 filelock-3.12.4 future-0.18.3 identify-2.5.30 idna-3.4 iniconfig-2.0.0 iso8601-2.1.0 isort-5.12.0 kombu-5.3.2 mccabe-0.7.0 nodeenv-1.8.0 numpy-1.26.0 openpyxl-3.1.2 oteapi-core-0.5.2 otelib-0.3.2 packaging-23.2 paramiko-3.3.1 pint-0.22 platformdirs-3.11.0 pluggy-1.3.0 pre-commit-3.4.0 prompt-toolkit-3.0.39 psycopg-3.1.12 psycopg2-binary-2.9.9 pycparser-2.21 pydantic-1.10.13 pylint-3.0.1 pynacl-1.5.0 pysftp-0.2.9 pytest-7.4.2 pytest-cov-4.1.0 python-dateutil-2.8.2 pyyaml-6.0.1 requests-2.31.0 six-1.16.0 tomli-2.0.1 tomlkit-0.12.1 tripper-0.2.9 typing-extensions-4.8.0 tzdata-2023.3 urllib3-1.26.17 vine-5.0.0 virtualenv-20.24.5 wcwidth-0.2.8`

**Comment by CasperWA** [comment]
Is the reason not actually psycopg2-binary as you also imply in your PR #178? `Removed psycopg2-binary from requirements. It is not needed and leads to segfault.`

**Comment by ajeklund** [comment]
> Is the reason not actually psycopg2-binary as you also imply in your PR #178? `Removed psycopg2-binary from requirements. It is not needed and leads to segfault.` It would be good to know whether the issue is the psycopg2-binary or DLite or the interaction between these. If it has anything to do with DLite - it's something that should be able to be remedied there as well.

https://github.com/EMMC-ASBL/oteapi-dlite/pull/178 was merged on October 16th, so `psycopg2-binary` should now have been removed.

**Comment by CasperWA** [comment]
After removing `psycopg2-binary` completely from any requirements files, this seems to work now. This was done in #176
