### ISSUE TITLE
Usage of plugins defined in DLite

### ISSUE THREAD

**Issue by TorgeirUstad** [EMMC-ASBL/oteapi-dlite#2]
For creating DLite instances from files with valid instance information, we could use the storage plugins that are already implemented in DLite (e.g. BSON, CSV, YAML).

Wrappers for these plugins could be implemented manually, or we could write some code that can search/query for and interface to any available DLite plugin.

Note: DLite storage plugins can also be used for serializing instances to the same formats.

**Comment by jesper-friis** [comment]
Fixed in PR #82
