### ISSUE TITLE
Support pre-commit in Windows

### ISSUE THREAD

**Issue by ajeklund** [EMMC-ASBL/oteapi-dlite#214]
The `pre-commit` hook `update-docs-api-reference` fails on Windows because it uses the `grep` command. This has been fixed in [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd), which should probably be put in use for the `oteapi-dlite` repository.

**Comment by CasperWA** [comment]
This has been fixed - now using SINTEF/ci-cd pre-commit hook.
