### ISSUE TITLE
Reenable update-docs-api-reference in ci workflow

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-dlite#83]
Line 44 in .github/workflows/ci_tests.yml was changed from

      run: SKIP=pylint,pylint-tests pre-commit run --all-files

to

      run: SKIP=pylint,pylint-tests,update-docs-api-reference pre-commit run --all-files

since the `update-docs-api-reference` failed on github while worked locally.

**Comment by CasperWA** [comment]
When was this changed? Is this issue here to say that it should be changed back/fixed?

**Comment by jesper-friis** [comment]
> When was this changed? Is this issue here to say that it should be changed back/fixed?

Yes, this This is here to say that it should be changed back/fixed?
